# Generated by Django 3.2.4 on 2021-07-14 08:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tweets', '0006_alter_comment_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='retweet',
            unique_together={('user', 'tweet')},
        ),
    ]
